/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DaoCliente;
import controlador.DaoProducto;
import controlador.DaoVendedor;
import controlador.DaoVenta;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Producto;
import modelo.Vendedor;
import modelo.Venta;

/**
 *
 * @author Mabel
 */
public class AgregarVenta extends javax.swing.JFrame {

    
    List<Producto> lista_productos;
     List<Cliente> lista_clientes;
     List<Vendedor> lista_vendedores;
    
    JComboBox<String> cb_prod = new JComboBox<String>();
    ComboBoxModel<String> items_productos = cb_prod.getModel(); 
    JComboBox<String> cb_cli = new JComboBox<String>();
    ComboBoxModel<String> items_clientes = cb_cli .getModel();
    JComboBox<String> cb_ven= new JComboBox<String>();
    ComboBoxModel<String> items_vendedores = cb_ven .getModel();
    
    /**
     * Creates new form AgregarVenta
     */
    public AgregarVenta() {
        initComponents();
        cargarElementos();
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaVenta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblRutVend = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        cboCodProd = new javax.swing.JComboBox<>();
        cboCliente = new javax.swing.JComboBox<>();
        cboVendedor = new javax.swing.JComboBox<>();
        lblRutCli1 = new javax.swing.JLabel();
        lblRutCli = new javax.swing.JLabel();
        lblCodProd = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jdcFechaVenta = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        lblRutVend.setText("RUT VENDEDOR:");

        lblFechaVenta.setText("FECHA VENTA:");

        cboCodProd.setModel(items_productos);
        cboCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodProdActionPerformed(evt);
            }
        });

        cboCliente.setModel(items_clientes);
        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        cboVendedor.setModel(items_vendedores);
        cboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVendedorActionPerformed(evt);
            }
        });

        lblRutCli1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRutCli1.setText("AGREGAR VENTA");

        lblRutCli.setText("RUT CLIENTE:");

        lblCodProd.setText("CÓDIGO PRODUCTO:");

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(54, 54, 54)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRutCli)
                                .addGap(54, 54, 54)
                                .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRutVend)
                                .addGap(41, 41, 41)
                                .addComponent(cboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodProd)
                                    .addComponent(lblFechaVenta))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboCodProd, 0, 139, Short.MAX_VALUE)
                                    .addComponent(jdcFechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRutCli1)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRutCli1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutCli)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutVend)
                    .addComponent(cboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProd)
                    .addComponent(cboCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaVenta)
                    .addComponent(jdcFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar(){
        cargarElementos();
        Calendar clndr = null;
        jdcFechaVenta.setCalendar(clndr);
        
    }
    public void cargarElementos(){
        try {
            /////// OBtiene elementos
        DaoProducto dao = new DaoProducto();
        lista_productos= dao.listarProductos();            
        List<String> lista_productos_str = new ArrayList<String>();
        for (Producto x : lista_productos) {
            lista_productos_str.add(String.valueOf(x.getCodigo()));
        }
        
         DaoCliente daoc = new DaoCliente();
        lista_clientes= daoc.listarClientes();            
        List<String> lista_clientes_str = new ArrayList<String>();
        for (Cliente x : lista_clientes) {
            lista_clientes_str.add(x.getRut());
        }
        
         DaoVendedor daov = new DaoVendedor();
        lista_vendedores= daov.listarVendedores();            
        List<String> lista_vendedores_str = new ArrayList<String>();
        for (Vendedor x : lista_vendedores) {
            lista_vendedores_str.add(x.getRut());
        }
        
///////// creacion comobox
        if (items_productos instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itempro = (DefaultComboBoxModel) items_productos;
        itempro.removeAllElements();
        itempro.addElement("");
            for (String value : lista_productos_str) {
                itempro.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
        
        
         if (items_clientes instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itemcli = (DefaultComboBoxModel) items_clientes;
        itemcli.removeAllElements();
        itemcli.addElement("");
            for (String value : lista_clientes_str) {
                itemcli.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
         
         
                  if (items_vendedores instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itemven = (DefaultComboBoxModel) items_vendedores;
        itemven.removeAllElements();
        itemven.addElement("");
            for (String value : lista_vendedores_str) {
                itemven.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
        } catch (Exception e) {
        }


        
    }
    
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (cboCliente.getSelectedItem().equals("")||cboCodProd.getSelectedItem().equals("")||cboVendedor.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar todas las opciones.");
        }else{
            Cliente cli = new Cliente();
            for (Cliente x : lista_clientes) {
                if (x.getRut().equalsIgnoreCase(cboCliente.getSelectedItem().toString())) {
                    cli = x;
                }
        }
        
            Vendedor vend = new Vendedor();
            for (Vendedor x : lista_vendedores) {
                if (x.getRut().equalsIgnoreCase(cboVendedor.getSelectedItem().toString())) {
                    vend = x;
                }
        }
        
            Producto prod = new Producto();
            for (Producto x : lista_productos) {
                if (Integer.toString(x.getCodigo()).equalsIgnoreCase(cboCodProd.getSelectedItem().toString())) {
                    prod = x;
                }
        }
            
        java.util.Date fechaVenta = jdcFechaVenta.getDate();
        
        
            DaoVenta dv = new DaoVenta();
            Venta vent = new Venta(fechaVenta, prod, vend, cli);
            dv.agregarVenta(vent);
            JOptionPane.showMessageDialog(rootPane, "Las opciones ingresadas han sido guardadas.");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        

        
        
        
        
        /*Cliente cli = new Cliente();
        try {
            for (Cliente x : lista_clientes) {
                if (x.getRut().equalsIgnoreCase(cboCliente.getSelectedItem().toString())) {
                    cli = x;
                }
            }
        } catch (Exception e) {
        }
        
        try {
            String rutCli = txtRutCli.getText();
            String rutVend = txtRutVend.getText();
            int codigo = Integer.parseInt(txtCodProd.getText());
            Date fechaVenta = Date.valueOf(txtFechaVenta.getText());

            Venta vent = new Venta(fechaVenta, codigo, rutVend, rutCli, null, null,null);

            DaoVenta dao = new DaoVenta();
            boolean r =dao.agregarVenta(vent);
            if (r) {
                JOptionPane.showMessageDialog(rootPane, "Venta agregado");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Venta no agregado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cboCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodProdActionPerformed
        
    }//GEN-LAST:event_cboCodProdActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClienteActionPerformed

    private void cboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboCodProd;
    private javax.swing.JComboBox<String> cboVendedor;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcFechaVenta;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblRutCli;
    private javax.swing.JLabel lblRutCli1;
    private javax.swing.JLabel lblRutVend;
    private javax.swing.JTextField txtFechaVenta;
    // End of variables declaration//GEN-END:variables
}
