/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mabel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        CantVentDiaVendedor = new javax.swing.JMenuItem();
        ValorRecaudadoDyM = new javax.swing.JMenuItem();
        LitrosCompradosCliente = new javax.swing.JMenuItem();
        ProdVendidos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AgregarAuto = new javax.swing.JMenuItem();
        EliminarVendedor = new javax.swing.JMenuItem();
        ModificarVendedor = new javax.swing.JMenuItem();
        ListarVendedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AgregarCliente = new javax.swing.JMenuItem();
        EliminarCliente = new javax.swing.JMenuItem();
        ModificarCliente = new javax.swing.JMenuItem();
        ListarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AgregarProducto = new javax.swing.JMenuItem();
        EliminarProducto = new javax.swing.JMenuItem();
        ModificarProducto = new javax.swing.JMenuItem();
        ListarProducto = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        AgregarVent = new javax.swing.JMenuItem();
        EliminarVent = new javax.swing.JMenuItem();
        ModificarVent = new javax.swing.JMenuItem();
        ListarVent = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar1.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Ink Free", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("La Pureza");

        jLabel1.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dedicada al envasado y despacho de Agua Purificada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        CantVentDiaVendedor.setText("Cantidad de ventas diarias por vendedor");
        CantVentDiaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantVentDiaVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(CantVentDiaVendedor);

        ValorRecaudadoDyM.setText("Valor recaudado diario y mensual");
        ValorRecaudadoDyM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorRecaudadoDyMActionPerformed(evt);
            }
        });
        jMenu1.add(ValorRecaudadoDyM);

        LitrosCompradosCliente.setText("Litros comprados por cliente");
        LitrosCompradosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LitrosCompradosClienteActionPerformed(evt);
            }
        });
        jMenu1.add(LitrosCompradosCliente);

        ProdVendidos.setText("Productos mas vendidos");
        ProdVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdVendidosActionPerformed(evt);
            }
        });
        jMenu1.add(ProdVendidos);

        barraMenu.add(jMenu1);

        jMenu2.setText("Vendedor");

        AgregarAuto.setText("Agregar ");
        AgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAutoActionPerformed(evt);
            }
        });
        jMenu2.add(AgregarAuto);

        EliminarVendedor.setText("Eliminar ");
        EliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(EliminarVendedor);

        ModificarVendedor.setText("Modificar ");
        ModificarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(ModificarVendedor);

        ListarVendedor.setText("Listar");
        ListarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(ListarVendedor);

        barraMenu.add(jMenu2);

        jMenu3.setText("Cliente");

        AgregarCliente.setText("Agregar");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(AgregarCliente);

        EliminarCliente.setText("Eliminar ");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(EliminarCliente);

        ModificarCliente.setText("Modificar ");
        ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(ModificarCliente);

        ListarCliente.setText("Listar");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(ListarCliente);

        barraMenu.add(jMenu3);

        jMenu4.setText("Producto");

        AgregarProducto.setText("Agregar");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });
        jMenu4.add(AgregarProducto);

        EliminarProducto.setText("Eliminar");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });
        jMenu4.add(EliminarProducto);

        ModificarProducto.setText("Modificar");
        ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoActionPerformed(evt);
            }
        });
        jMenu4.add(ModificarProducto);

        ListarProducto.setText("Listar");
        ListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProductoActionPerformed(evt);
            }
        });
        jMenu4.add(ListarProducto);

        barraMenu.add(jMenu4);

        jMenu7.setText("Venta");

        AgregarVent.setText("Agregar");
        AgregarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVentActionPerformed(evt);
            }
        });
        jMenu7.add(AgregarVent);

        EliminarVent.setText("Eliminar");
        EliminarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentActionPerformed(evt);
            }
        });
        jMenu7.add(EliminarVent);

        ModificarVent.setText("Modificar");
        ModificarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVentActionPerformed(evt);
            }
        });
        jMenu7.add(ModificarVent);

        ListarVent.setText("Listar");
        ListarVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarVentActionPerformed(evt);
            }
        });
        jMenu7.add(ListarVent);

        barraMenu.add(jMenu7);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAutoActionPerformed
        AgregarVendedor av = new AgregarVendedor();
        av.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_AgregarAutoActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        AgregarCliente ac = new AgregarCliente();
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void EliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVendedorActionPerformed
        EliminarVendedor ev = new EliminarVendedor();
        ev.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarVendedorActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        EliminarCliente ec = new EliminarCliente();
        ec.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteActionPerformed
        ModificaCli mc = new ModificaCli();
        mc.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ModificarClienteActionPerformed

    private void ModificarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVendedorActionPerformed
        ModificaVende mv = new ModificaVende();
        mv.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarVendedorActionPerformed

    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
        ListarCliente lc = new ListarCliente();
        lc.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarClienteActionPerformed

    private void ListarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarVendedorActionPerformed
        ListarVendedor lv = new ListarVendedor();
        lv.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarVendedorActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
        AgregarProducto ap = new AgregarProducto();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        EliminarProducto ep = new EliminarProducto();
        ep.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarProductoActionPerformed

    private void ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoActionPerformed
        ModificarPro mp = new ModificarPro();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarProductoActionPerformed

    private void ListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProductoActionPerformed
        ListarProducto lp = new ListarProducto();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarProductoActionPerformed

    private void AgregarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVentActionPerformed
        AgregarVenta av = new AgregarVenta();
        av.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarVentActionPerformed

    private void ModificarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVentActionPerformed
        ModificarVenta mv = new ModificarVenta();
        mv.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarVentActionPerformed

    private void EliminarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentActionPerformed
        EliminarVenta ev = new EliminarVenta();
        ev.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarVentActionPerformed

    private void ListarVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarVentActionPerformed
        ListarVenta lv = new ListarVenta();
        lv.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarVentActionPerformed

    private void ValorRecaudadoDyMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorRecaudadoDyMActionPerformed
        ValorRecaudadoDM vrdm=new ValorRecaudadoDM();
        vrdm.setVisible(true);
        dispose();
    }//GEN-LAST:event_ValorRecaudadoDyMActionPerformed

    private void CantVentDiaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantVentDiaVendedorActionPerformed
        CantidadVentasDV cvdv=new CantidadVentasDV();
        cvdv.setVisible(true);
        dispose();
    }//GEN-LAST:event_CantVentDiaVendedorActionPerformed

    private void LitrosCompradosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LitrosCompradosClienteActionPerformed
        LitrosClienteCantidad lcc = new LitrosClienteCantidad();
        lcc.setVisible(true);
        dispose();
    }//GEN-LAST:event_LitrosCompradosClienteActionPerformed

    private void ProdVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdVendidosActionPerformed
       ProdVendidos prodv = new ProdVendidos();
       prodv.setVisible(true);
       dispose();
    }//GEN-LAST:event_ProdVendidosActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarAuto;
    private javax.swing.JMenuItem AgregarCliente;
    private javax.swing.JMenuItem AgregarProducto;
    private javax.swing.JMenuItem AgregarVent;
    private javax.swing.JMenuItem CantVentDiaVendedor;
    private javax.swing.JMenuItem EliminarCliente;
    private javax.swing.JMenuItem EliminarProducto;
    private javax.swing.JMenuItem EliminarVendedor;
    private javax.swing.JMenuItem EliminarVent;
    private javax.swing.JMenuItem ListarCliente;
    private javax.swing.JMenuItem ListarProducto;
    private javax.swing.JMenuItem ListarVendedor;
    private javax.swing.JMenuItem ListarVent;
    private javax.swing.JMenuItem LitrosCompradosCliente;
    private javax.swing.JMenuItem ModificarCliente;
    private javax.swing.JMenuItem ModificarProducto;
    private javax.swing.JMenuItem ModificarVendedor;
    private javax.swing.JMenuItem ModificarVent;
    private javax.swing.JMenuItem ProdVendidos;
    private javax.swing.JMenuItem ValorRecaudadoDyM;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
