/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DaoCliente;
import controlador.DaoProducto;
import controlador.DaoVendedor;
import controlador.DaoVenta;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Producto;
import modelo.Vendedor;
import modelo.Venta;

/**
 *
 * @author Mabel
 */
public class ModificarVenta extends javax.swing.JFrame {

    
    List<Producto> lista_productos;
     List<Cliente> lista_clientes;
     List<Vendedor> lista_vendedores;
    
    JComboBox<String> cb_prod = new JComboBox<String>();
    ComboBoxModel<String> items_productos = cb_prod.getModel(); 
    JComboBox<String> cb_cli = new JComboBox<String>();
    ComboBoxModel<String> items_clientes = cb_cli .getModel();
    JComboBox<String> cb_ven= new JComboBox<String>();
    ComboBoxModel<String> items_vendedores = cb_ven .getModel();
    
    /**
     * Creates new form AgregarVenta
     */
    
    /**
     * Creates new form ModificarVenta
     */
    public ModificarVenta() {
        initComponents();
        cargarElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFechaVenta = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblRutVend = new javax.swing.JLabel();
        cboVendedor = new javax.swing.JComboBox<>();
        lblRutCli = new javax.swing.JLabel();
        cboCodProd = new javax.swing.JComboBox<>();
        lblCodProd = new javax.swing.JLabel();
        lblModificarVenta = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        lblRut2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jdcFechaVenta = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        lblFechaVenta.setText("FECHA VENTA:");

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblRutVend.setText("RUT VENDEDOR:");

        cboVendedor.setModel(items_vendedores);

        lblRutCli.setText("RUT CLIENTE:");

        cboCodProd.setModel(items_productos);
        cboCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodProdActionPerformed(evt);
            }
        });

        lblCodProd.setText("CODIGO PRODUCTO:");

        lblModificarVenta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblModificarVenta.setText("MODIFICAR VENTA");

        cboCliente.setModel(items_clientes);
        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        lblRut2.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        lblRut2.setText("EJ: 2021-11-23");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblModificarVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRutVend)
                            .addComponent(lblRutCli)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodProd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFechaVenta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboVendedor, 0, 177, Short.MAX_VALUE)
                            .addComponent(cboCodProd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcFechaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRut2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblModificarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutCli)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutVend)
                    .addComponent(cboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProd)
                    .addComponent(cboCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(lblFechaVenta))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblRut2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jdcFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnVolver)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if (cboCliente.getSelectedItem().equals("")||cboCodProd.getSelectedItem().equals("")||cboVendedor.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar todas las opciones.");
        }else{
            Cliente cli = new Cliente();
            for (Cliente x : lista_clientes) {
                if (x.getRut().equalsIgnoreCase(cboCliente.getSelectedItem().toString())) {
                    cli = x;
                }
            }

            Vendedor vend = new Vendedor();
            try {
                for (Vendedor x : lista_vendedores) {
                    if (x.getRut().equalsIgnoreCase(cboVendedor.getSelectedItem().toString())) {
                        vend = x;
                    
                }
            }
            } catch (Exception e) {
            }
            

            Producto prod = new Producto();
            for (Producto x : lista_productos) {
                if (Integer.toString(x.getCodigo()).equalsIgnoreCase(cboCodProd.getSelectedItem().toString())) {
                    prod = x;
                }
            }

            java.util.Date fechaVenta = jdcFechaVenta.getDate();
            
            DaoVenta dv = new DaoVenta();
            
            
                    
            Venta vent = new Venta(fechaVenta, prod, vend, cli);
            dv.modificarVenta(vent);
            JOptionPane.showMessageDialog(rootPane, "Las opciones ingresadas han sido modificadas.");
        }

        /*Cliente cli = new Cliente();
        try {
            for (Cliente x : lista_clientes) {
                if (x.getRut().equalsIgnoreCase(cboCliente.getSelectedItem().toString())) {
                    cli = x;
                }
            }
        } catch (Exception e) {
        }

        try {
            String rutCli = txtRutCli.getText();
            String rutVend = txtRutVend.getText();
            int codigo = Integer.parseInt(txtCodProd.getText());
            Date fechaVenta = Date.valueOf(txtFechaVenta.getText());

            Venta vent = new Venta(fechaVenta, codigo, rutVend, rutCli, null, null,null);

            DaoVenta dao = new DaoVenta();
            boolean r =dao.agregarVenta(vent);
            if (r) {
                JOptionPane.showMessageDialog(rootPane, "Venta agregado");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Venta no agregado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodProdActionPerformed

    }//GEN-LAST:event_cboCodProdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       try {
           
            String rutCli = String.valueOf(cboCliente.getSelectedItem());
            String rutVend = String.valueOf(cboVendedor.getSelectedItem());
            int codigoProd = Integer.parseInt(cboCodProd.getSelectedItem().toString());
            
            DaoVenta dao = new DaoVenta();
            Venta ven = dao.buscarVenta(rutCli, rutVend, codigoProd);

            if (cboCliente.getSelectedItem().equals("")||cboCodProd.getSelectedItem().equals("")||cboVendedor.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(rootPane, " No se han encontrado los datos buscados");
            }else {
                jdcFechaVenta.setDate(ven.getFechaVenta());
                
                

                cboCliente.setEnabled(false);
                cboCodProd.setEnabled(false);
                cboVendedor.setEnabled(false);
                
                
                btnBuscar.setEnabled(false);
                btnModificar.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void limpiar(){
        cargarElementos();
        ;
    }
    
    
    
    public void cargarElementos(){
        try {
            /////// OBtiene elementos
        DaoProducto dao = new DaoProducto();
        lista_productos= dao.listarProductos();            
        List<String> lista_productos_str = new ArrayList<String>();
        for (Producto x : lista_productos) {
            lista_productos_str.add(String.valueOf(x.getCodigo()));
        }
        
         DaoCliente daoc = new DaoCliente();
        lista_clientes= daoc.listarClientes();            
        List<String> lista_clientes_str = new ArrayList<String>();
        for (Cliente x : lista_clientes) {
            lista_clientes_str.add(x.getRut());
        }
        
         DaoVendedor daov = new DaoVendedor();
        lista_vendedores= daov.listarVendedores();            
        List<String> lista_vendedores_str = new ArrayList<String>();
        for (Vendedor x : lista_vendedores) {
            lista_vendedores_str.add(x.getRut());
        }
        
///////// creacion comobox
        if (items_productos instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itempro = (DefaultComboBoxModel) items_productos;
        itempro.removeAllElements();
        itempro.addElement("");
            for (String value : lista_productos_str) {
                itempro.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
        
        
         if (items_clientes instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itemcli = (DefaultComboBoxModel) items_clientes;
        itemcli.removeAllElements();
        itemcli.addElement("");
            for (String value : lista_clientes_str) {
                itemcli.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
         
         
                  if (items_vendedores instanceof DefaultComboBoxModel) {
        DefaultComboBoxModel itemven = (DefaultComboBoxModel) items_vendedores;
        itemven.removeAllElements();
        itemven.addElement("");
            for (String value : lista_vendedores_str) {
                itemven.addElement(value);
            }
            //Object selectedItem = items_productos.getSelectedItem();
        }
/////////////////////////////
        } catch (Exception e) {
        }

        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboCodProd;
    private javax.swing.JComboBox<String> cboVendedor;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcFechaVenta;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblModificarVenta;
    private javax.swing.JLabel lblRut2;
    private javax.swing.JLabel lblRutCli;
    private javax.swing.JLabel lblRutVend;
    // End of variables declaration//GEN-END:variables
}
